---
deployment:
  tasks:
    - /usr/bin/rsync -rl --exclude='.git' --exclude='.cpanel.yml' --exclude='.gitignore' --exclude='.gitkeep' /home/tibaaiuz/repositories/tibaai/ /home/tibaaiuz/public_html/ --delete --exclude='generated' --exclude='tmp' --exclude='.env' --exclude='data/*.db' --exclude='data/*.sqlite'
    - mkdir -p /home/tibaaiuz/public_html/generated /home/tibaaiuz/public_html/tmp /home/tibaaiuz/public_html/data
    - chmod 755 /home/tibaaiuz/public_html/generated /home/tibaaiuz/public_html/tmp /home/tibaaiuz/public_html/data
